name: Code Formatter

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # allows manual runs

jobs:
  format:
    name: Run Ruff Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ruff
        run: pip install ruff

      - name: Check formatting
        run: ruff format --check .
